export const APP_DIRECTORIES = {
  ROOT_PATH: '',
  APP_DIR: '',
  BACKUP_DIR: '',
  DOWNLOAD_DIR_ANDROID: '',
  EXPORT_FILES_ANDROID: '',
  EXPORT_FILES_IOS: '',
  SHARED_DOCUMENTS_PATH_IOS: '',
  IMAGES: '',
  TILE_CACHE: '',
  TILES_DIRECTORY: '',
  TILE_TEMP: '',
  TILE_ZIP: '',
};
