// MAPS
// export const CURRENT_BASEMAP = 'CURRENT_BASEMAP';
// export const CUSTOM_MAPS = 'CUSTOM_MAPS';
// export const DELETE_OFFLINE_MAP = 'DELETE_OFFLINE_MAP';
// export const MAP = 'MAP';
// export const OFFLINE_MAPS = 'OFFLINE_MAPS';


// FEATURES
// export const FEATURE_ADD = 'FEATURE_ADD';
// export const FEATURE_DELETE = 'FEATURE_DELETE';
// export const FEATURE_SELECTED = 'FEATURE_SELECTED';
// export const FEATURES_SELECTED_CLEARED = 'FEATURES_SELECTED_CLEARED';
// export const FEATURES_UPDATED = 'FEATURES_UPDATED';
//
// export const EDIT_SPOT_PROPERTIES = 'EDIT_SPOT_PROPERTIES';
// export const EDIT_SPOT_GEOMETRY = 'EDIT_SPOT_GEOMETRY';
// export const SET_ISONLINE = 'SET_ISONLINE';

//IMAGES
// export const ADD_PHOTOS = 'ADD_PHOTOS';
// export const DELETE_PHOTOS = 'DELETE_PHOTOS';
// export const EDIT_SPOT_IMAGES = 'EDIT_SPOT_IMAGES';

//FORMS
// export const SET_FORM_DATA = 'SET_FORM_DATA';

// VISIBLE PAGES
// export const SET_NOTEBOOK_PAGE_VISIBLE = 'SET_NOTEBOOK_PAGE_VISIBLE';
// export const SET_SPOT_PAGE_VISIBLE = 'SPOT_PAGE_VISIBLE';

