require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  install! 'cocoapods', :deterministic_uuids => false

platform :ios, '12.1'

target 'StraboSpot2' do
  config = use_native_modules!
    inherit! :complete

  use_react_native!(:path => config["reactNativePath"])
  ReactNativeMapboxGLIOSVersion = '~> 6.1'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#   use_flipper!({ 'Flipper-Folly' => '2.6', 'Flipper' => '0.91.2' })
#  post_install do |installer|
#     flipper_post_install(installer)
#   end
 pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'

 post_install do |installer|
#      flipper_post_install(installer)
    $RNMBGL.post_install(installer)
  end
end

target 'StraboSpot2-tvOS' do
  # Pods for StraboSpot2-tvOS

  target 'StraboSpot2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

pre_install do |installer|
  fix_mapbox_events(installer)
end

pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end

