require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'StraboSpot2' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

    # Pods Added
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

   # Mapbox
    pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  target 'StraboSpot2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'StraboSpot2-tvOS' do
  # Pods for StraboSpot2-tvOS

  target 'StraboSpot2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
